### ISSUE TITLE
Validator is in the wrong package and got the wrong name?

### ISSUE THREAD

**Issue by rbygrave** [avaje/avaje-validator#10]
Right now, I think Validator is not the public API that users of avaje-validator would learn, know and use ... but instead it's a bit more spice / internal with lots of functionality that is there for code generation and for people looking to extend it with their own custom annotations / validation.

In my mind, Validator is moved into the `adapter` package along with `AnnotationValidationAdapter` and given some other name.

In my mind the public API is a lot more minimal, just:
- bootstrap
- validate(Object) 
- obtain a ValidationType<T>

Today the Validator does a tonne more stuff and 99% of that imo should be hidden from the casual user that just wants to get the validator and validate an object.  Hence I'd love to move Validator and AnnotationValidationAdapter into the adapter package and rename Validator to something else.

**Comment by SentryMan** [comment]
what would be the mechanism then, for users to create custom validation annotations? That's basically the reason I moved the `AnnotationValidationAdapter` into public package. I can imagine a few scenarios where somebody would want to create custom validations. (validating enums match a specific value for example)

**Comment by rbygrave** [comment]
> users to create custom validation annotations

Those users still need public API and my thought is that the api for that would be in the `adapter` package.  

It's more that there is a heck of a lot less of these types of users compared to the number of the users that just ... get the validator and validate an instance. Currently we are presenting a really big API to cater for these 2 different types of users of the api.

**Comment by SentryMan** [comment]
> - obtain a ValidationType

I don't think we really need to expose this bit, since we get the same result calling with `validate(Object)`

**Comment by rbygrave** [comment]
> I don't think we really need to expose this bit

Agree.  ValidationType can be removed.

**Comment by SentryMan** [comment]
> Agree. ValidationType can be removed.

well, we still kinda need it, but I don't think it should be exposed as a public interface.

**Comment by rbygrave** [comment]
I think we can close this.  The PR there has pulled out the `adapter()` methods from `Validator` and moved them to what is currently called `AdapterContext`.  Might not be what we end up with but I'll close this for now I think.
