### ISSUE TITLE
`@NotBlank(max=...)` - include Max Length validation with `@NotBlank`

### ISSUE THREAD

**Issue by rbygrave** [avaje/avaje-validator#103]
In reviewing some validation cases there is the very common case of on Strings of:
- `@NotBlank @Size(max=...)` 
- `@NotBlank @Length(max=...)`   ... basically the same

Now although this is all good as it is per se I'm mindful of "Annotation Overload" which is that we have code with soooo many annotations that it detracts from the whole thing.

With this in mind I think its this very common case with String input in particular where I think it might be nice to support a `@NotBlank(max=...)` such that the common case only needs 1 annotation.

Hmm, pondering ...

**Comment by SentryMan** [comment]
> @NotBlank(max=...) would use 2 messages - the {avaje.NotBlank.message} and the {avaje.Length.max.message}.

idk, seems a little weird to me that a single annotation would have two messages.

**Comment by rbygrave** [comment]
> idk, seems a little weird to me that a single annotation would have two messages.

I agree in that this is generally correct (and there would only be 2 messages if they don't override the message). This would be that exception to the rule so could be a bit "left field" - the justification is along the lines that 99% of strings should have some max length validation. 

I'll see if I can get something close to satisfying.

**Comment by rbygrave** [comment]
I tried both a single combined message via a new `{avaje.NotBlank.max.message}` and the 2 separate messages and ultimately it felt better with the 2 separate error messages - one for "Not Blank" and the other for "Max length".
