### ISSUE TITLE
Should there be a @Required. (as a @NotNull / @NotBlank) ?

### ISSUE THREAD

**Issue by rbygrave** [avaje/avaje-validator#106]
There are other validation libs that use "Required" rather than "Not Null". (C#, Playframework, HTML forms)

To me  _"must not be null"_ is pretty developer centric way of saying that a particular property is required. To me the "{field} is required" sounds better.

It could be that the message is the question but I like `@Required` because It really says "I'm a validation requirement" and `@NotNull` could be confused with types / type system / all those "@Nullable / @NonNull" annotations.

**Comment by SentryMan** [comment]
> @NotNull could be confused with types / type system / all those "https://github.com/nullable / @nonnull" annotations.

We already work with `@Nonnull` too.

**Comment by rbygrave** [comment]
It's more I'd like `@Required` to be an **_alias_** for `@NotNull` (and `@NotBlank` for String/CharSequence). 

It's more about user confusing / user facing.  For myself I'd prefer to annotate domain objects with `@Required`.

**Comment by rbygrave** [comment]
> We already work with @Nonnull too

I'm cool with that btw - that's all good by me.

**Comment by rbygrave** [comment]
I think the reason we don't have a Required is because there are differences between NotNull / NotBlank / NotEmpty. 

I'm kind of punting on the idea that Required can mean NotNull (or NotBlank for strings) and that NotEmpty is really only going to be used for collection types (and not really used for string types).

**Comment by SentryMan** [comment]
> "I'm a validation requirement"

"In what way is this required?" Is the question that will pop up when people see the annotation. Just saying something is required sounds ambiguous to me. Saying clearly that that things failed because it was blank or null is more my style.

**Comment by SentryMan** [comment]
Say also we have a `List<@Required String>` field, it looks off to me.

**Comment by rbygrave** [comment]
> `List<@Required String> field`, it looks off to me

Yes, agreed. I'd not use Required there though, more like:

```java
@Required String firstName;
@Required String lastName;
@Required @Email String email;
@Required LocalDate startDate;
@Required UUID globalId;
@Required Address address;

```
vs 

```java
@NotBlank String firstName;
@NotBlank String lastName;
@NotNull @Email String email;
@NotNull LocalDate startDate;
@NotNull UUID globalId;
@NotNull Address address;

```

> Just saying something is required sounds ambiguous to me.

Maybe but PHP Laravel and dotNet both use "Required".  So I'm suggesting a lot of people out there use "Required" (but not Jakarta validation folks).

**Comment by rbygrave** [comment]
> In what way is this required?

In web development we have form fields that are required to be entered. Back in the day the'd have a little red `*` to indicate  the "required fields", and the error message back to the user was along the lines ... _"first name is required"_ 

Hmm.

**Comment by rbygrave** [comment]
Ok, I think we can ditch this idea - stick with what we have.  I'll close this now.
