### ISSUE TITLE
Should validators chain another way (in order to share instances, esp NotNull, use less memory)

### ISSUE THREAD

**Issue by rbygrave** [avaje/avaje-validator#11]
Currently the generated code chains validator instances using `andThen()` and a closure like:

https://github.com/avaje/avaje-validator/blob/main/validator/src/test/java/io/avaje/validation/core/CustomerValidationAdapter.java#L30-L32

My thought is that a very large proportion of the time the first validation check is NotNull, and a lot of the time there will be no customisation of that notNull check (no custom message etc). We could look to share the same instance of the NotNull validator in that case but to do so we need to reverse the chaining ... instead of using `andThen()` it would need to be nested by parent.

That is, we could save some memory by looking to share validator instances that are stateless (no custom message or annotation params - e.g. NotNull, Past, Future NotBlank, NotEmpty).

**Comment by SentryMan** [comment]
If you can think of a better one, I'm all for it, I just did the first thing that came to mind

**Comment by SentryMan** [comment]
not sure if sharing instances would work that well, as each validation pojo might use the same adapter, but with different messages. (some might even want to use custom messages with `@NonNull`)

**Comment by rob-bygrave** [comment]
I had a little look and my gut told me that what we have at the moment looks "natural" to me ... we'd need to get a good win to change it around.  I'll have another look later ...

**Comment by rbygrave** [comment]
I'll close this for now, lets leave it as it is.
