### ISSUE TITLE
Add Validator.check() methods that return Set<ConstraintViolation> rather than throw

### ISSUE THREAD

**Issue by rbygrave** [avaje/avaje-validator#113]
Refer to: https://github.com/avaje/avaje-validator/commit/d5ad073d5573b5a5fdffd01dc381c3813747f70d

Technically we might not need this but I think it could be useful for applications that want to pre-validate messages before sending them etc.

Unfortunately I'm managed to just push this to main instead of a PR.  

Let me know what you think and we can remove if we don't like it.

**Comment by SentryMan** [comment]
I'm pretty sure I asked for this at some point

**Comment by SentryMan** [comment]
it seems https://github.com/avaje/avaje-validator/pull/80 lives on in spirit

**Comment by rbygrave** [comment]
Yup. I'm still not sure tbh

**Comment by SentryMan** [comment]
one thing is that it doesn't work in failfast mode

**Comment by rbygrave** [comment]
In the view that people SHOULD be testing their validation ... then this check() method [or a method that returns the violations] is definitely nicer to use.

So my thought is that we have this method even if it is only used for that purpose. That leaves me with:
- Consuming the Set is kind of a pain, should this return a **_List_** instead?
- If this returns a List, should the ConstraintViolationException also be a List rather than Set?

If List is used that really really really means that ordering is expected and locked in. So sounds like Set is better (even if we wrap it in a List for testing purposes)?

**Comment by rbygrave** [comment]
Ok, I'm getting comfortable that its good to have **_both_** `validate()` _throws_ and `check()` _returns Set_

I'm also thinking stick to Set over List.

If you are happy we can close this issue?

**Comment by SentryMan** [comment]
Sure

**Comment by rbygrave** [comment]
Ok, closing.
