### ISSUE TITLE
Remove CoreValidation / DCoreValidation ... require() with NotNullAdapter 

### ISSUE THREAD

**Issue by rbygrave** [avaje/avaje-validator#13]
We can remove CoreValidation / DCoreValidation I think

**Comment by SentryMan** [comment]
I was thinking kinda the opposite way, that someone would add `@Nullable` to say that a field is optional.

**Comment by rob-bygrave** [comment]
I think that was my very bad description.  I was trying to say ... we removed the CoreValidation.collection() method and I think we should also remove the CoreValidation.require() method from the internals.
