### ISSUE TITLE
Not null by default, maybe do that via @ValidPojo?

### ISSUE THREAD

**Issue by rob-bygrave** [avaje/avaje-validator#14]
> that someone would add @Nullable to say that a field is optional.

Yes, we could make `Non Null` the default and have an attribute like `@ValidPojo(nullableByDefault=true)` to allow someone to change the default on a per type basis?  

We could also detect the avaje-lang `@NonNullApi` on package or class?

**Comment by SentryMan** [comment]
> We could also detect the avaje-lang `@NonNullApi` on package or class?

Idk, sounds like a hassle, if we make the default non-null, we don't need to do any detection.

**Comment by rob-bygrave** [comment]
ok cool, so we'll look to go not null by default ... and ignore `@NonNullApi` for now and see how we go.

I'll close this issue. I might create some new issues on tasks I have in mind like:
- Review how the message is actually formatted in hibernate validator - like `{jakarta.validator.NotBlank.message}` etc
- Add a placeholder for validation using the groups / classes (maybe we support this, maybe not)
- Add the missing constraint annotations to avaje-constraints
- Add some more tests 

I think we can start code generation work too.

**Comment by SentryMan** [comment]
> * Review how the message is actually formatted in hibernate validator - like `{jakarta.validator.NotBlank.message}` etc

I figured I would use Avaje config to interpolate it (would prepend a $ and eval it)

> * Add a placeholder for validation using the groups / classes (maybe we support this, maybe not)

I never used that feature, so I have no opinion.

> I think we can start code generation work too.

neat

**Comment by rbygrave** [comment]
I think we can close this one now right?

**Comment by rob-bygrave** [comment]
I'll close this one I think.
