### ISSUE TITLE
Add a @Compare(otherField)  with GT, GTE, LT, LTE operators ?

### ISSUE THREAD

**Issue by rob-bygrave** [avaje/avaje-validator#144]
Example use:
```java
LocalDate startDate;

@GreaterThan("startDate")
LocalDate endDate;
```

```java
BigDecimal retailPrice;

@GreaterThan("retailPrice")
BigDecimal offerPrice;
```

So this is a bit like class level validation in that it should only validate after all the per field validation has completed and request.hasViolations() is false.  Only perform multi-field comparison validation if field validation has passed ok.

Alternatively, this could more generally be:

```java
@Compare(operator=Operator.GT|GTE|LT|LTE, with="startDate", orNull=true|false)
```

This feels like it might need a new interface like:

```java
interface ValidationCompare<T> {

   boolean validate(T value, Operator op, T otherValue, ValidationRequest req, String propertyName)
}
```

**Comment by SentryMan** [comment]
I like `@Compare` better, but I'm not totally sold on the idea since this can already be done with class constraints.

**Comment by rbygrave** [comment]
Closing this for now.
