### ISSUE TITLE
Should artifact io.avaje:validator-constraints be renamed to io.avaje:avaje-validator-constraints

### ISSUE THREAD

**Issue by rob-bygrave** [avaje/avaje-validator#174]
So rename the artifactId from `validator-constraints` to `avaje-validator-constraints` which makes it more consistent (and I believe is the generally preferred convention for artifactId's these days).

**Comment by SentryMan** [comment]
sounds good to me I suppose

**Comment by SentryMan** [comment]
as long as we don't change any package names should be fine
