### ISSUE TITLE
Method validation without raising exception

### ISSUE THREAD

**Issue by jeusdi** [avaje/avaje-validator#202]
I've took a look on [method validation documentation](https://avaje.io/validator/#methods).

I've also realazed that [`@ValidMethod` annotation](https://github.com/avaje/avaje-validator/blob/main/validator/src/main/java/io/avaje/validation/ValidMethod.java#L18) has a field named `throwOnParamFailure`.

I'd like to know if methods like this could be resolved:

```java
public Either<String,DummyError> dummyMethod(@NotNull String name);
```

Could something like above code be resolved?

I mean, when any violation is checked by method validation return according return method signature.

**Comment by SentryMan** [comment]
So in that case the method would return `DummyError`?. Not sure how that could be done.

**Comment by jeusdi** [comment]
Let me explain me better:

### Problem Description

My code raises exceptions only in exceptional cases (database connectivity, ...). For example, validation rules have to be checked and mapped to domain error objects.

That means that service layer methods which are meant to check business rules can run with a success result or a no-success result. [Here explains better what I mean](https://www.sandromaglione.com/articles/either-error-handling-functional-programming#functional-programming-error-handling).

### Goal

I want to handle validation errors internally within the service layer and return a `Result` (or `Either`) object that encapsulates both success and error states without relying on exception handling mechanisms like `@ControllerAdvice`.

### Code Example

Here is my `DummyError` class:

```java
import lombok.Builder;
import lombok.Data;

import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;

import jakarta.validation.ConstraintViolation;

@Data
@Builder
public class DummyError {

    private String message;
    private List<String> violations;

    public static DummyError fromConstraintViolations(Set<ConstraintViolation<?>> violations) {
        List<String> violationMessages = violations.stream()
            .map(violation -> violation.getPropertyPath() + " " + violation.getMessage())
            .collect(Collectors.toList());

        return DummyError.builder()
            .message("Validation failed")
            .violations(violationMessages)
            .build();
    }
}
```

Here is my `DummyService` class first approach without using `@ValidMethod`:

```java
@Component
@RequiredArgsConstructor
public class DummyService {

    private final Validator validator;

    public Result<String, DummyError> dummyMethod(String name) {
        // Validate the parameter 'name'
        Set<ConstraintViolation> violations = //how to check `name` here without using @ValidMethod way

        if (!violations.isEmpty()) {
            return Result.ofErr(DummyError.fromConstraintViolations(violations));
        }

        return Result.ofOK("Hello " + name);
    }
}
```

Using ``@ValidMethod` approach:

```java
public class DummyService {

    private final Validator validator;

    @ValidMethod
    public Result<String, DummyError> dummyMethod(@NotNull String name) {
        return Result.ofOK("Hello " + name);
    }
}
```

Above code is only an approach that what I'm trying to get.

### Explanation

1. **DummyError Class:**
    - The `DummyError` class includes a static method `fromConstraintViolations` that constructs an instance of `DummyError` from a set of `ConstraintViolation`.
    - This method iterates over the violations and creates a list of error messages to populate the `DummyError` object.

2. **DummyService Class:**
    - The service class uses a `Validator` to validate the `name` parameter using the `validateValue` method.
    - If there are any violations, a `Result` with the error (`Result.ofErr`) is returned, constructed using the `fromConstraintViolations` method.
    - If there are no violations, a success `Result` (`Result.ofOK`) with the greeting message is returned.
    - The `getName` method is a dummy getter to satisfy the validation requirement.

### Conclusion

1. How to check single value parameter by code.
2. Could be there anyway to customize AOP interceptor result type using any kind of kustomizer in order to adapt validation constraints to desired output method?

**Comment by SentryMan** [comment]
You can use try-catch wherever you call the method validator. 
```java

public class DummyService {
    @ValidMethod
    public String dummyMethod(@NotNull String name) {
        return "Hello " + name;
    }
}
```

```java
try {
  DummyService service = //...

  service.dummyMethod(null);
} catch (ConstraintViolationException ex) {
// do something
}
```

Otherwise, I currently can't see a way to do this. Not even spring has a function like this.
