### ISSUE TITLE
Make annotation processor lombok friendly

### ISSUE THREAD

**Issue by kliushnichenko** [avaje/avaje-validator#259]
Lost some time trying to figure out why the validations are failing with `UnsupportedOperationException: null`.  
It turns out the validator is incompatible with the Lombok.

When the order of processors is:
1. lombok processor
2. avaje-validator-generator

Some extra `ValidationAdapter`s are generated for getters, and they fail with   
```
java.lang.UnsupportedOperationException: null
        at jars//io.avaje.validation.adapter.ValidationAdapter.primitive(ValidationAdapter.java:39)
 ```
        
Changing the order won't help either, compilation simply fails:
```
[ERROR] Non accessible field .... name with no matching getter?
[ERROR] Error ValidationAdapter due to nonAccessibleField for ....
```

**Comment by SentryMan** [comment]
works for me?

Do you have an example class I can try to reproduce with?

**Comment by SentryMan** [comment]
I've tried with

```java
@Valid
@Getter
public class RequestModel2 {

  @Positive private int value;
  @NotBlank private String str;

  @NotNull
  private String method() {
    return str;
  }
}
```

with the following maven config

```xml
    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
      <version>1.18.34</version>
      <scope>provided</scope>
    </dependency>

    <dependency>
      <groupId>io.avaje</groupId>
      <artifactId>avaje-validator-generator</artifactId>
      <version>2.2</version>
      <scope>provided</scope>
    </dependency>
```

and it compiles fine. 

It's notable though that if I place avaje before lombok it doesn't compile. Naturally, as lombok modifies the class during APT there's nothing I can do about it other than tell people to have lombok run first.

**Comment by kliushnichenko** [comment]
Interesting.

Here is an example project https://github.com/kliushnichenko/jooby-sandbox/tree/avaje-validator-lombok
This is a Jooby project, but without `jooby-apt`, `jooby-avaje-validator` to avoid any possible side-effects from them.  

Validation is triggered when app is started. Run `mvn jooby:run` to startup.

**Comment by SentryMan** [comment]
Ah I see the issue, will have a fix out later today
