### ISSUE TITLE
make the annotation adapter use instanceof to check the type and do validation

### ISSUE THREAD

**Issue by rbygrave** [avaje/avaje-validator#7]
> I'm thinking for annotations that accept multiple unrelated types we make the annotation adapter use instanceof to check the type and do validation

Do you an example?  I'm not sure I fully understand this yet ...

**Comment by SentryMan** [comment]
> > I'm thinking for annotations that accept multiple unrelated types we make the annotation adapter use instanceof to check the type and do validation
> 
> Do you an example? I'm not sure I fully understand this yet ...

For example the siae annotation is supposed to work on arrays, char sequence and collections

**Comment by SentryMan** [comment]
So for the size adapter, I've made it so that it takes an Object and does the casting needed to do the validations

**Comment by SentryMan** [comment]
this should only be needed when the types the annotation supports have no common interface
