### ISSUE TITLE
Specific annotations vs mapping known multiple annotations

### ISSUE THREAD

**Issue by rbygrave** [avaje/avaje-validator#9]
If we look at the jakarta validation annotations, they are included in the jakarta-validation-api and this API comes with LOTS of stuff. More bluntly LOTS of stuff we don't really want or want people to know or think about or get confused by because it contains something that semantically conflicts/confuses in some way with what we have with avaje-validator.

IF the jakarta validation annotations where in their own artefact by themselves I would have no hesitation in just always using them but they don't and that api comes with a lot of cruft.

https://jakarta.ee/specifications/bean-validation/3.0/apidocs/

So with that in mind I had in mind the plan to have an artefact that only has validation annotations ... and that exists here - https://github.com/avaje/avaje-validator/tree/main/validator-constraints/src/main/java/io/avaje/validation/constraints
... and yes these annotations largely mirror the same matching annotations that are here - https://jakarta.ee/specifications/bean-validation/3.0/apidocs/jakarta/validation/constraints/package-summary.html

My thought was that we have for example 2 `@Size` annotations and at compile time they are translated into the same validation code. That is, my thought was that both jakarta `@Size` and avaje-validation `@Size` are known to us and map to the same generated code.

**Comment by SentryMan** [comment]
> My thought was that we have for example 2 @Size annotations and at compile time they are translated into the same validation code.

We can do that now with the current implementation, we could export the current adapters to the avaje constraint module which would provide a factory to match it's annotations with the core adapters. (if you notice the adapters are not actually specific to jakarata).

**Comment by rbygrave** [comment]
> do that now with the current implementation

Yes, although we currently have a "hard" dependency on Jakarta-validation-api right?  On the annotation classes as opposed to say Strings?

So I think what we have is close but don't we need to adjust to remove the dependency there in the JakartaTypeAdapters? So that it doesn't use the Jakarta annotation classes? Maybe I misunderstood that part?

**Comment by SentryMan** [comment]
> Yes, although we currently have a "hard" dependency on Jakarta-validation-api right? On the annotation classes as opposed to say Strings?

the only jakarta bit I'm using is:

```
  @SuppressWarnings({"unchecked", "rawtypes"})
  static final AnnotationValidationAdapter.Factory FACTORY =
      (annotationType, validator, interpolator) -> {
        if (annotationType == AssertTrue.class) return new AssertTrueAdapter(interpolator);
        if (annotationType == NotBlank.class) return new NotBlankAdapter(interpolator);
        if (annotationType == Past.class) return new PastAdapter(interpolator);
        if (annotationType == Pattern.class) return new PatternAdapter(interpolator);
        if (annotationType == Size.class) return new SizeAdapter(interpolator);
        return null;
      };
```
I could switch this with the avaje one if we so desire. or even just use the canonical name to pick the adapters.

**Comment by rbygrave** [comment]
> could export the current adapters to the avaje constraint module which would provide a factory to match it's annotations with the core adapters.

In my head, the ideal is that the annotations live by themselves away from the adapters / factory / implementations.

> if you notice the adapters are not actually specific to Jakarta

Yes, its more that mapping of the annotations to the adapters ... currently uses the annotation types.  In my mind, the generator could know how to map all the known annotation types (both avaje and jakarta) and somehow we avoid the mapping by annotation for these well known cases.

**Comment by rbygrave** [comment]
> just use the canonical name to pick the adapters

Basically this, or a "well known short name / String".

Something like, we stick to annotations for the general custom validation annotations, but for well known jakarata/avaje annotations we instead use string canonical or short name.

**Comment by SentryMan** [comment]
> Basically this, or a "well known short name / String".

I have implemented it.

**Comment by SentryMan** [comment]
> if you notice the adapters are not actually specific to Jakarta

ah, hmm, seems I was incorrect, the Pattern Adapter depends on Jakarta

**Comment by rbygrave** [comment]
At the moment,  but we can get the code generator to extract the flags as a set of int values
