### ISSUE TITLE
Pondering passing the actual value type when creating the validator ... (to optimise number comparison checks)

### ISSUE THREAD

**Issue by rbygrave** [avaje/avaje-validator#95]
For example, if `Long.class` is passed for Min/Max/Range check the implementation doesn't need the extra `instanceof` checks.

**Comment by SentryMan** [comment]
this is one of the main benefits of having the JDK 21 switch matching I believe.

**Comment by rbygrave** [comment]
We need to change the generated code to pass the type in order to use that to then optimise the number based validators.
